= Python Course: Lesson 1
Lorenzo Cabrini <lorenzo.cabrini@gmail.com>
:icons: font
:source-highlighter: coderay
:experimental:
:pdf-page-size: 9in x 6in
:title-page:

<<<

== Welcome!

You are going to learn to program in *Python*.

<<<

== Before we Begin

This is a very *practical* course.

NOTE: In order to become a programmer you will need to write *a lot of code*.

<<<

"You can't learn to fly a plane by watching slides. The same is true for programming."

<<<

This is also a very *active* course.

NOTE: "You need to do the thinking, not me."

<<<

This doesn't mean that *theory* is not important in programming. It is.

However, you need to build up some practical skills first.

<<<

== What you will need

To get started you will need:

* Python 3.6 or later
* a text editor
* a terminal ("Command prompt" for Windows users)

NOTE: Later in the course you will need a few other things. We will set things up when we need them.

<<<

== Good to Have

It is a good idea to download the Python 3 *documentation* on your system, especially if you don't have constant Internet access: https://docs.python.org.

Always keep a *notebook* and a few *pens* around when you are programming.

<<<

== Preparing your System

To begin with we are going to make sure you have a Python 3 environment and a text editor installed on your system.

WARNING: This course uses Python 3. Make sure you have the right version installed.

<<<

== Pause

We will pause for a few minutes to make sure everybody has a working environment set up.

If you already have Python 3 running on your system and a text editor that you like, you can take *a few minutes* to stretch your legs.

<<<

== Interactive Python

We are going to get to know Python by using the *Interactive Mode*.

<<<

To start the Interactive Mode, open a terminal and type:

[listing]
----
% python3
----

NOTE: From this point on, I will use `%` to indicate the shell prompt. Don't type this.

<<<

You should see something like the following:

[listing]
----
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
----

NOTE: We want to make sure everybody is in the Python Interactive environment. If you can, help your neighbor!

<<<

The >>> you see is the *prompt*. When you see this it means Python is ready for you to type statements that it will process.

<<<

== A Very Basic Expression

Type 12 at the prompt and hit enter. What happens?

[listing]
----
>>> 12
----

<<<

That's right. Python echoed the 12 back to you.

[listing]
----
>>> 12
12
----

NOTE: If you got some different output, raise your hand so that we can help you get it right.
